-I$IP_HOME/uvm/src
-I$IP_HOME/rtl
-I$IP_HOME/tb
$IP_HOME/uvm/src/uvm_pkg.sv
$IP_HOME/rtl/alu_decoder.sv
$IP_HOME/rtl/alu_core.sv
$IP_HOME/rtl/alu.sv
$IP_HOME/tb/alu_tb_pkg.sv
$IP_HOME/tb/alu_if.sv
$IP_HOME/tb/alu_tb_top.sv
